language: csharp
matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      dotnet: 1.0.0-preview2-1-003177
      mono: none
      env: DOTNETCORE=1
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-1-003177
      mono: none
      env: DOTNETCORE=1
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-1-003177
      mono: latest             
install:
- dotnet restore
before_script:
- sh -e /etc/init.d/xvfb start
solution: "./Promact.OAuth.Client/Promact.OAuth.Client.sln"
notifications:
  email:
    on_success: change
    on_failure: always
script:
  - if [ -n "${DOTNETCORE}" ]; then 
      dotnet build && dotnet test; 
    else 
      nuget restore ./Promact.OAuth.Client/Promact.OAuth.Client.sln && xbuild ./Promact.OAuth.Client/Promact.OAuth.Client.sln 
    fi  
